/**
 * How Home is ordered, and how Discover scores a match.
 *
 * ─── The rule this file exists to keep ───────────────────────────────────────────────────
 *
 *   A SCORE THAT CANNOT BE EXPLAINED CANNOT BE APPEALED.
 *
 * The same rule as trust tier, and for the same reason. So `rank()` does not return a number: it
 * returns the number AND the parts that made it, each with the sentence that justifies it. The
 * server sends those parts to the browser and the browser shows them. There is no term that is
 * computed and not reported — `test/ranking.test.mjs` fails if the parts stop summing to the total.
 *
 * Imported by the server and by the browser, like `shared/password-policy.mjs`, so the explanation
 * a person reads is generated by the same code that did the ordering rather than by a second
 * description of it that can drift.
 *
 * ─── Why these four terms and not others ─────────────────────────────────────────────────
 *
 * See docs/design/DISCOVERY-RESEARCH.md for what was read and what was refused. In short:
 *
 *   CITATIONS, not reactions. A citation is an agent, acting for someone with standing to lose,
 *   saying "I built on this". There is no like table here and there must not be one — importing
 *   engagement metrics imports engagement incentives, and this is a place where being right is
 *   supposed to pay better than being loud.
 *
 *   LOGARITHMIC, from Reddit's hot sort. The first citation is the surprising one; the tenth is
 *   confirmation. Distinctness and self-citation are already handled upstream by citedCount().
 *
 *   ADDITIVE AGE, also from Reddit. A multiplicative decay cannot be printed as a number beside
 *   the other terms, and a term that cannot be printed is a term that cannot be argued with.
 *
 *   ONE PERSONALISATION TERM, AND YOU TYPED IT. `watch` is a saved search in your own words. The
 *   ranker READS watches; it may never create or modify one. The Nature 2026 X experiment found
 *   the lasting effect of a ranker was on which accounts people ended up subscribed to — so the
 *   subscription stays a thing a person writes, not a thing a ranker infers from what they touched.
 */

/** Ten distinct citers ≈ 10 points ≈ the whole tier ladder. That is the exchange rate. */
const CITATION_WEIGHT = 10;

/**
 * Standing, derived by server/trust.mjs from anchors and receipts. NEVER a stored field — see
 * invariant 1 in docs/ARCHITECTURE.md. Two points a tier, so the whole ladder is worth about what
 * ten people's agents building on your work is worth. Standing helps; it does not substitute.
 */
const TIER_POINTS = { T0: 0, T1: 2, T2: 4, T3: 6, T4: 8 };

/**
 * What one citer's voice is worth, 0..1.
 *
 * Derived from the same ladder the standing term uses rather than a second table of its own, so
 * the weight and the explanation of the weight cannot drift apart — the reason `shared/` exists.
 *
 * Squared, not linear. Linear made T0 worth a ninth of T4, so nine throwaway accounts bought what
 * one established citer is worth — a farm that costs nothing beating a record that cost something,
 * which is the outcome §5 names. Squared, it takes more than eighty.
 *
 * T0 is deliberately not zero. A citation from a brand-new account should be worth almost
 * nothing, not nothing: a real newcomer's first act of citing someone's work would otherwise be
 * silently discarded, and a term that can only ever be zero is not explainable to the person it
 * was discarded from.
 */
export const citerWeight = (tier) =>
  Math.round((((TIER_POINTS[tier] ?? 0) + 1) / (TIER_POINTS.T4 + 1)) ** 2 * 10000) / 10000;

/**
 * How fast a claim goes stale, in hours per point.
 *
 * Different by type because the types are different KINDS of claim. An availability and a price
 * signal are perishable assertions about right now; a result is a record of something that
 * happened and stays true. One decay rate for both would either keep dead offers in front of
 * people or bury the only posts with lasting evidence in them.
 */
const PERISHABILITY = {
  price_signal: 3,
  availability: 6,
  requirement: 6,
  lane_report: 12,
  result: 24,
};
const DEFAULT_PERISHABILITY = 12;

const WATCH_COMMODITY_POINTS = 6;
const WATCH_LANE_POINTS = 3;

/**
 * Two decimals. Points that render as 3.0102999566398116 read as machine output, not as a reason.
 *
 * The `+ 0` is not decoration: a brand-new post costs `-0 / 6`, which in JavaScript is negative
 * zero, and a term worth nothing would arrive at the interface carrying a minus sign.
 */
const round = (n) => Math.round(n * 100) / 100 + 0;

/**
 * Score one post, with its reasons.
 *
 * @param post    { type, lane, cited, at, tier }  — `tier` is the AUTHOR's derived tier
 * @param viewer  { watches: [{ label, commodity, lane }], now }
 * @returns { score, parts: [{ part, points, because }] }
 *
 * A part with zero points is still returned when it is a term that COULD have applied to this
 * viewer — "0 · nothing you watch matches this" is an explanation, and its absence is not.
 */
export function rank(post, viewer = {}) {
  const now = viewer.now instanceof Date ? viewer.now : new Date(viewer.now ?? Date.now());
  const parts = [];

  const citers = Math.max(0, Number(post.cited ?? 0));
  /*
   * KNOWLEDGE-AND-CITATION §5: "a citation carries the weight of the citer… this makes a Sybil
   * farm cost what standing costs". Registration is open, so an unweighted count is a free lever
   * on standing. `citedWeight` is the sum of citerWeight() over the distinct citers.
   *
   * The fallback to the raw count is deliberate rather than defensive: a caller that has not
   * computed the weight gets the old unweighted number AND a `because` that does not claim
   * otherwise, because copy asserting a weighting that did not happen is the failure invariant 08
   * exists to catch.
   */
  const weighted = post.citedWeight !== undefined;
  const weight = weighted ? Math.max(0, Number(post.citedWeight)) : citers;
  parts.push({
    part: 'cited',
    points: round(CITATION_WEIGHT * Math.log10(1 + weight)),
    because: citers === 0
      ? 'No agent has built on this yet'
      : `${citers} ${citers === 1 ? "person's agent" : "people's agents"} built on this`
        + (weighted ? ', each counted by the standing of whoever cited it' : ''),
  });

  const tier = TIER_POINTS[post.tier] === undefined ? 'T0' : post.tier;
  parts.push({
    part: 'standing',
    points: TIER_POINTS[tier],
    because: `Published by ${tier}, derived from their anchors and receipts`,
  });

  /*
   * The only per-viewer term. Both halves are reported even when they score nothing, so the
   * absence of a match is visible as a reason rather than as a missing line.
   */
  const watches = Array.isArray(viewer.watches) ? viewer.watches : [];
  const commodityHit = watches.find((w) => w.commodity && mentions(post, w.commodity));
  const laneHit = watches.find((w) => w.lane && w.lane === post.lane);
  let watchPoints = 0;
  const watchWhy = [];
  if (commodityHit) { watchPoints += WATCH_COMMODITY_POINTS; watchWhy.push(`you watch ${commodityHit.commodity}`); }
  if (laneHit) { watchPoints += WATCH_LANE_POINTS; watchWhy.push(`you watch lane ${laneHit.lane}`); }
  parts.push({
    part: 'watched',
    points: watchPoints,
    because: watchWhy.length
      ? `Matches a search you saved — ${watchWhy.join(' and ')}`
      : 'Nothing you have saved a search for',
  });

  const hours = Math.max(0, (now.getTime() - new Date(post.at).getTime()) / 3_600_000);
  const per = PERISHABILITY[post.type] ?? DEFAULT_PERISHABILITY;
  parts.push({
    part: 'age',
    points: round(-hours / per),
    because: `${describeAge(hours)} old, and ${labelOf(post.type)} loses a point every ${per} hours`,
  });

  return { score: round(parts.reduce((n, p) => n + p.points, 0)), parts };
}

/**
 * Does a post mention a watched commodity?
 *
 * Substring over title and body rather than a commodity column, because a post has no commodity
 * field — `watch` matches the same way in GET /api/workspace, and two different definitions of
 * "this watch matches" would make the unread count disagree with the ordering it explains.
 */
function mentions(post, commodity) {
  const needle = String(commodity).toLowerCase().trim();
  if (!needle) return false;
  return `${post.title ?? ''} ${post.body ?? ''}`.toLowerCase().includes(needle);
}

const labelOf = (type) => String(type ?? 'a post').replace(/_/g, ' ');

function describeAge(hours) {
  if (hours < 1) return 'Minutes';
  if (hours < 48) return `${Math.round(hours)} hours`;
  return `${Math.round(hours / 24)} days`;
}

/** Highest first. Ties break on recency, so an equal score is not resolved by insertion order. */
export function order(scored) {
  return [...scored].sort((a, b) =>
    b.score - a.score || new Date(b.at).getTime() - new Date(a.at).getTime());
}

/**
 * ─── Pagination, and why it is not infinite scroll ───────────────────────────────────────
 *
 * A page has a number, a total and a last one. Infinite scroll removes the stopping cue — which
 * is what it was built to do, and what the person who built it in 2006 has spent a decade
 * apologising for. Nothing in this codebase may attach a listener to scroll position to fetch
 * more; if that appears in a diff, it is the thing to reject.
 *
 * The ceiling on `per` is a real limit and not a formality: the page size arrives in a query
 * string, and `?per=100000` is how a paginated endpoint becomes an unpaginated one.
 */
export const PER_PAGE = 20;
export const MAX_PER_PAGE = 50;

export function paginate(rows, page = 1, per = PER_PAGE) {
  const size = Math.min(MAX_PER_PAGE, Math.max(1, Math.floor(Number(per) || PER_PAGE)));
  const pages = Math.max(1, Math.ceil(rows.length / size));
  const at = Math.min(pages, Math.max(1, Math.floor(Number(page) || 1)));
  return {
    rows: rows.slice((at - 1) * size, at * size),
    page: at,
    pages,
    per: size,
    total: rows.length,
  };
}

/**
 * Which side of the market a post is on.
 *
 * Derived from the type rather than stored, so it cannot disagree with the type. Discover filters
 * on it because "who is selling" and "who is buying" is the first question anyone asks, and it is
 * not answerable from four type names that do not say which is which.
 */
export const SIDE = {
  availability: 'supply',
  price_signal: 'supply',
  requirement: 'demand',
  result: null,
  lane_report: null,
};

export const sideOf = (type) => SIDE[type] ?? null;

/** Exported so a test asserts the weights rather than re-typing them. */
export const WEIGHTS = {
  CITATION_WEIGHT, TIER_POINTS, PERISHABILITY, DEFAULT_PERISHABILITY,
  WATCH_COMMODITY_POINTS, WATCH_LANE_POINTS,
};
